---
title: Comparing Methods for Constructing Confidence Intervals
subtitle: A 95% Coverage Analysis of Four Approaches
author: Blessing Ofori-Atta
format: revealjs
embed-resources: true
---

# Introduction and Methods

## Symmetric Bootstrap-t (Plug-in Estimate of Standard Error)

1. Consistently estimate $\theta$ and $se(\hat{\theta})$ using the observed sample (the simulated data): $\hat{\theta}$, $\hat{se}(\hat{\theta})$. 
2. Generate a bootstrap sample $X_1^\star, \dots, X_n^*$.
3. Compute $\hat{\theta}^\star_b$, $\hat{se}^\star_b(\hat{\theta})$, and $$T^\star_b=\frac{\hat{\theta}^\star_b-\hat{\theta}}{\hat{se}^\star_b (\hat{\theta})}$$ based on the bootstrap sample generated in step 1, where $\hat{\theta}^\star_b$ and $\hat{se}^\star_b(\hat{\theta})$ are estimates of the parameter $\theta$ and its standard error. 
4. Repeat steps 1 and 2 $B$ times to obtain $T^\star_b, b=1, \dots, B$.
5. Order the bootstrap replications of $T$ such that $|T^\star_{1}| \leq |T^\star_{2}| \leq \dots \leq |T^\star_{B}|$. The absolute critical value, $c$, is determined as the $(1-\alpha)B$-th element.If $\alpha B$ is not an integer, $c$ is the largest integer $<= (1-\alpha)(B+1)$. For $B=999$ and $\alpha=5\%$ this is the 950th ordered element. Now a $1-\alpha$ confidence interval for $\theta$ is $$\hat{\theta} \pm |T^\star_{c}|.\hat{se}(\hat{\theta})$$

## Symmetric Bootstrap-t (Boostrap Estimate of Standard Error)

1. Repeat steps 1-3. In step 3, instead of using the plug-in estimate of the standard error for the bootstrap sample, Generate another bootstrap sample from $X_1^\star, \dots, X_n^*$ and estimate the standard error $\hat{se}^\star_b(\hat{\theta})$. 
2. Repeats steps 4-5. 

## Percentile Method

1. Repeat steps 1-2. In step 2, compute $\hat{\theta}^\star_b$ only. 
2. Order the bootstrap replications of $\hat{\theta}$ such that $\hat{\theta}^\star_{1} \leq \hat{\theta}^\star_{2} \leq \dots \leq \hat{\theta}^\star_{B}$. The lower and upper confidence bounds are the $B.\alpha/2$-th and $B(1-\alpha/2)$-th ordered elements, respectively. A $1-\alpha$ confidence interval for $\theta$ is $\left[\hat{\theta}^\star_{B.\alpha/2}, \hat{\theta}^\star_{B(1-\alpha/2)}\right]$.

## Wald Method

1. Constructs a $1-\alpha$ confidence interval for the population mean using the formula $$\hat{\theta} \pm z_{1-\alpha/2}.\hat{se}(\hat{\theta})$$ where $z_{1-\alpha/2}$ is the $(1-\alpha/2)$ quantile of the standard normal distribution.

## Simulation Design

- The simulation involved generating $n \in {10, 20, 50, 100, 200}$ observations from an exponential distribution with mean one. 
- For each sample size, $mcrep=1000$ replications of the observed data, were generated, and 95% confidence intervals were constructed using above methods. 
- The coverage rate, defined as the proportion of replications in which the true mean $(\mu =1)$ fell within the confidence interval, was calculated.


## Preliminary Results


